version: '3.8'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: school
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:

