version: "3.8" 
services: 
  web1: 
    build: 
      context: ./python 
      dockerfile: ../customdirdockerfile/dockfile23 
      args: 
        PYTHON_VERSION: "3.10" 
    image: myflaskapp 
    container_name: flask-app-container-1 
    ports: 
      - "5000:5000" 
    networks: 
      - app-network1 
    depends_on: 
      - redis1 
    environment: 
      - REDIS_HOST=redis1 
 
  redis1: 
    image: redis:alpine 
    container_name: redis-container1  
 
    networks: 
      - app-network1 
    volumes: 
      - ./adhana:/data 
      - redis1-volume:/extra-data2 
 
  web2: 
    build: 
      context: ./python 
      dockerfile: ../customdirdockerfile/dockfile23 
      args: 
        PYTHON_VERSION: "3.9" 
    image: myflaskapp 
    container_name: flask-app-container-2 
    ports: 
      - "5001:5000" 
    networks: 
      - app-network2 
    depends_on: 
      - redis2 
    environment: 
      - REDIS_HOST=redis2 
 
  redis2: 
    image: redis:alpine 
    container_name: redis-container2 
    networks: 
      - app-network2 
    volumes: 
      - ./gujjar:/data 
      - redis2-volume:/extradata2 
 
networks: 
  app-network1: 
  app-network2: 
volumes: 
  redis1-volume: 
  redis2-volume: 
